#include "diri.h"

#include "codegen_llvm.h"
#include "diag.h"
#include "lexer.h"
#include "parser.h"
#include "sema.h"
#include "token.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static char *read_file(const char *path) {
    FILE *file;
    long size;
    char *buffer;

    file = fopen(path, "rb");
    if (file == NULL) {
        diri_error("failed to open input file: %s", path);
        return NULL;
    }

    if (fseek(file, 0, SEEK_END) != 0) {
        fclose(file);
        return NULL;
    }

    size = ftell(file);
    if (size < 0) {
        fclose(file);
        return NULL;
    }

    rewind(file);
    buffer = (char *)malloc((size_t)size + 1);
    if (buffer == NULL) {
        fclose(file);
        return NULL;
    }

    if (fread(buffer, 1, (size_t)size, file) != (size_t)size) {
        free(buffer);
        fclose(file);
        return NULL;
    }

    buffer[size] = '\0';
    fclose(file);
    return buffer;
}

static void dump_tokens(const char *source) {
    DiriLexer lexer;
    DiriToken token;

    diri_lexer_init(&lexer, source);
    do {
        token = diri_lexer_next(&lexer);
        diri_info("token %-12s '%.*s' @ %d:%d",
                  diri_token_kind_name(token.kind),
                  token.length,
                  token.lexeme,
                  token.line,
                  token.column);
    } while (token.kind != DIRI_TOKEN_EOF && token.kind != DIRI_TOKEN_INVALID);
}

static int write_text_file(const char *path, const char *contents) {
    FILE *file = fopen(path, "wb");
    size_t len;

    if (file == NULL) {
        diri_error("failed to open output file: %s", path);
        return 1;
    }
    len = strlen(contents);
    if (fwrite(contents, 1, len, file) != len) {
        fclose(file);
        diri_error("failed to write output file: %s", path);
        return 1;
    }
    fclose(file);
    return 0;
}

static int diri_create_project(const DiriOptions *options) {
    char command[1024];
    char path[512];
    char readme[1024];
    char gitignore[256];
    const char *name = options->project_name != NULL ? options->project_name : "app";
    const char *main_source =
        "extern func print_str(x: str): void;\n"
        "extern func print_int(x: int): void;\n"
        "\n"
        "func banner(title: str): int {\n"
        "    print_str(title);\n"
        "    return 0;\n"
        "}\n"
        "\n"
        "func main(): int {\n"
        "    let i: int = 0;\n"
        "    let total: int = 0;\n"
        "\n"
        "    banner(\"hello from diri\");\n"
        "\n"
        "    while i < 5 {\n"
        "        total = total + i;\n"
        "        i = i + 1;\n"
        "    }\n"
        "\n"
        "    print_int(total);\n"
        "    return 0;\n"
        "}\n";

    snprintf(command, sizeof(command), "mkdir -p \"%s\"", name);
    if (system(command) != 0) {
        diri_error("failed to create project directory: %s", name);
        return 1;
    }

    snprintf(path, sizeof(path), "%s/main.di", name);
    if (write_text_file(path, main_source) != 0) {
        return 1;
    }

    snprintf(path, sizeof(path), "%s/.gitignore", name);
    snprintf(gitignore, sizeof(gitignore), "build/\n*.ll\n*.c\n");
    if (write_text_file(path, gitignore) != 0) {
        return 1;
    }

    snprintf(path, sizeof(path), "%s/README.md", name);
    snprintf(readme, sizeof(readme),
             "# %s\n\n"
             "This project was generated by `diri new`.\n\n"
             "Source files use the `.di` extension.\n\n"
             "## Run\n\n"
             "```sh\n"
             "diri run main.di\n"
             "```\n"
             "\n"
             "## Build\n\n"
             "```sh\n"
             "diri build main.di\n"
             "diri emit-ir main.di\n"
             "```\n"
             "\n"
             "## Watch\n\n"
             "```sh\n"
             "diri watch main.di\n"
             "```\n",
             name);
    if (write_text_file(path, readme) != 0) {
        return 1;
    }

    diri_info("created project '%s' with entry file %s/main.di", name, name);
    return 0;
}

int diri_driver_run(const DiriOptions *options) {
    char *source;
    DiriAstProgram *program;

    if (options == NULL) {
        diri_error("missing compiler options");
        return 1;
    }

    if (options->command == DIRI_CMD_NEW) {
        return diri_create_project(options);
    }

    if (options->input_path == NULL) {
        diri_error("no input file provided");
        return 1;
    }

    source = read_file(options->input_path);
    if (source == NULL) {
        return 1;
    }

    if (options->emit_tokens) {
        dump_tokens(source);
    }

    program = diri_parse_program(source);
    if (program == NULL || program->had_error) {
        diri_ast_program_free(program);
        free(source);
        return 1;
    }

    if (options->emit_ast) {
        diri_ast_dump_program(program);
    }

    if (diri_sema_check_program(program) != 0) {
        diri_ast_program_free(program);
        free(source);
        return 1;
    }

    if (diri_codegen_emit_llvm_ir(program, options->input_path) != 0) {
        diri_ast_program_free(program);
        free(source);
        return 1;
    }

    if (diri_codegen_build_native(program, options->input_path, options->run_after_build) != 0) {
        diri_ast_program_free(program);
        free(source);
        return 1;
    }

    if (options->emit_ir) {
        diri_info("emit-ir requested");
    }

    diri_ast_program_free(program);
    free(source);
    return 0;
}
